### ISSUE TITLE
USP compared to kafka mirror maker

### ISSUE THREAD

**Issue by cmeury** [ricardo-ch/kafka-topic-cloner#2]
What's the use case, or how will this tool be different from [mirror-maker](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=27846330)?

**Comment by EtienneGuerlais** [comment]
Mirrormaker is meant for replicating inside a secondary cluster, which means that simply moving the messages inside a single cluster raises some additional complexity, like renaming the topic on the fly (since it is supposed to re-publish into a topic that has the same name).
I found ways to do so, but it needed some class-writing every time to specify which topic needed to change name.

Also the main use-case of our tool was in case of hasher issues (messages with the same key assigned to different partitions), and I think that mirrormaker is mirroring partition-by-partition, which makes it not suitable for this use-case...
